username-generator.char=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789

app.seed.trainee-file=classpath:trainee-seed-data.json
app.seed.trainer-file=classpath:trainer-seed-data.json
app.seed.training-file=classpath:training-seed-data.json