spring:
  datasource:
    url: jdbc:postgresql://gym-db:5432/gymcrm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.example: DEBUG